### ISSUE TITLE
Test tree not firing up in browser

### ISSUE THREAD

**Issue by naveenjafer** [microsoft/adatest#10]
Hi Team! I was trying to get this up and running. I followed the instructions and notice that a tree does not open up in the browser and the process ends without any error. Is there any step that I am missing? I assume the process should ideally stay open as this is the server? I am using an anaconda environment. I would be happy to provide more details.

I have tried with both the package and directly from source, the result is the same in both the cases.

**Comment by Harsha-Nori** [comment]
Hi @naveenjafer, 

Hopefully Adatest is working for you now! For the benefit of future readers, we support two ways of launching the interactive visualization experience: 

- directly calling `tests.adapt(...)` in a Jupyter cell for an in-notebook experience
- calling `adatest.serve(tests.adapt(...), ip='127.0.0.1', port=8080)` to launch adatest as a hosted experience on a standalone (local) webserver (at the ip/port specified in the call)

Depending on your setup and IPython environment, there's a chance one of these methods may not be accessible (e.g. if you're in a cloud-hosted notebook environment). We recommend trying both, and if neither work, we're happy to help diagnose the issue.
